config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants, only: [:index, :new, :create, :show] do
    resources :reviews, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  CATEGORY = ['chinese', 'italian', 'japanese', 'french', 'belgian']
  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true, inclusion: { in: Restaurant::CATEGORY,
    message: 'it is not a valid category' }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :restaurant_id, presence: true
  validates :content, presence: true
  validates :rating, presence: true, numericality: { only_integer: true }, inclusion: { in: (0..5) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :category, :address, :phone_number)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
      <!-- Add these line for detecting device width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<h1>My restaurants</h1>
<ul>
    <% @restaurants.each do |restaurant| %>
  <li>
      <%= link_to restaurant.name, restaurant_path(restaurant) %>,
      <%= restaurant.category %>
  </li>
    <% end %>
</ul>

<%= link_to "Add a new restaurant", new_restaurant_path, class: "btn btn-primary" %>

app/views/restaurants/new.html.erb
<%= simple_form_for(@restaurant) do |f| %>
  <%= f.input :name %>
  <%= f.input :category, collection: Restaurant::CATEGORY %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.submit %>
<% end %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>

<div class="card" style="width: 18rem;">
  <div class="card-header">
    type: <%= @restaurant.category %>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">address: <%= @restaurant.address %></li>
    <li class="list-group-item">phone: <%= @restaurant.phone_number %></li>
  </ul>
</div>

<%= link_to "Add a review", new_restaurant_review_path(@restaurant)  %>
<%= link_to "Back to list", restaurants_path %>

<ul class="list-group">
  <% @restaurant.reviews.each do |review| %>
    <!-- <li class="list-group-item"><%= review.content %></li> -->
    <div class="card">
      <div class="card-header">
        Review
      </div>
      <div class="card-body">
        <blockquote class="blockquote mb-0">
          <p><%= review.rating %></p>
          <p><%= review.content %></p>
          <footer class="blockquote-footer">Someone famous in <cite title="Source Title">Le Wagon</cite></footer>
        </blockquote>
      </div>
    </div>
  <% end %>
</ul>

app/views/reviews/new.html.erb
<%= simple_form_for [ @restaurant, @review ] do |f| %>
  <%= f.input :rating %>
  <%= f.input :content %>
  <%= f.submit %>
<% end %>